### ISSUE TITLE
Feature request: ability to specific a message

### ISSUE THREAD

**Issue by mklatsky** [CenturyLinkLabs/zodiac#30]
When performing a "zodiac list", one of the columns specifies "MESSAGE", which looks to be used for rollbacks. It would be useful to have the ability to specify a message when performing a deploy, i.e.:

zodiac deploy -m "Update to version 3.10"

**Comment by patocox** [comment]
Hi @mklatsky Actually, that command will work as you describe. You can see more viewing help on the deploy command:
`$ zodiac deploy --help`

**Comment by mklatsky** [comment]
Well- so it does. Color me embarrassed. Thanks for the quick update :)
