### ISSUE TITLE
zodiac fails after docker-compose upgrade

### ISSUE THREAD

**Issue by mklatsky** [CenturyLinkLabs/zodiac#32]
zodiac is currently failing with and "Error: exit status 1". 
This error began after upgrading docker-machine, docker-swarm and docker-compose this morning. zodiac was working fine prior to the upgrade.

Debug log resulting from a 'zodiac deploy' is here: http://pastie.org/private/kl3s8ydqzdma6uc5dconug

Thank you.

**Comment by alexwelch** [comment]
Yeah, Zodiac does not work with Docker Compose 1.4 yet.

**Comment by alexwelch** [comment]
@mklatsky - what OS and architecture are you using? Any chance you'd be willing to kick the tires of a new binary for me (it's my initial pass at 1.4 support)?

**Comment by mklatsky** [comment]
I am on a Mac, OSX 10.10.4. 

I'd be glad to test the new binary:)

**Comment by alexwelch** [comment]
Greatly appreciated: Here's the very early compose 1.4 version of Zodiac: https://github.com/CenturyLinkLabs/zodiac/releases/tag/0.3.0... Let me know on this issue if you have any bugs, and thank you so much for being willing to kick the tires and help out!

**Comment by mklatsky** [comment]
So far, the version of zodiac you linked above works perfectly. I have tested the following:

zodiac deploy
zodiac deploy -m "Message"
zodiac rollback
zodiac list

All work as expected.

**Comment by alexwelch** [comment]
Great, really appreciate your feedback on this. I'll start prepping a "real" release. I'll let you know if I make any additional changes.

**Comment by alexwelch** [comment]
Here is the release: https://github.com/CenturyLinkLabs/zodiac/releases/tag/0.3.0... @mklatsky I'd go ahead and use a binary from the release as it has some minor changes.

Thanks again for helping test.
